name: Test Build

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'main'    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.0'
      - run: go build -ldflags='-w -s -extldflags "-static"' -a -o build/s3br cmd/s3-backup-restore/main.go
    